moyarsuccess/gathering

.gitignore
=> T14: remove google-services.json form .gitignore file

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/gathering/android/Application.kt, app/src/main/java/com/gathering/android/di/ApplicationModule.kt, build.gradle
Add an Application class
Add an Application module class
Add Hilt dependencies
Add dagger plugin and kept
@idaosk 
@moyar1532
=> [6] Add Hilt dependencies

app/build.gradle, app/google-services.json, app/src/main/AndroidManifest.xml, app/src/main/java/com/gathering/android/EventActivity.kt, app/src/main/java/com/gathering/android/intro/IntroActivity.kt, app/src/main/java/com/gathering/android/signUp/SignUpActivity.kt, app/src/main/java/com/gathering/android/signUp/SignUpScreenViewState.kt, app/src/main/java/com/gathering/android/signUp/SignUpViewModel.kt, app/src/main/java/com/gathering/android/signUp/model/AuthRepository.kt, app/src/main/java/com/gathering/android/signUp/model/ResponseState.kt, app/src/main/java/com/gathering/android/signUp/model/User.kt, app/src/main/res/layout/activity_event.xml, app/src/main/res/values/colors.xml, build.gradle
add  signUp viewModel and view states
add Firebase dependencies
add  google service json configure
add event activity page and resource
add sign up activity
add auth repository
=> T9: Add signUp page functionality (#9)

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/gathering/android/auth/signup/SignUpFragment.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewModel.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewState.kt, app/src/main/java/com/gathering/android/common/ActiveMutableLiveData.kt, app/src/main/java/com/gathering/android/common/ImageLoader.kt, app/src/main/java/com/gathering/android/common/ImageLoaderImp.kt, app/src/main/java/com/gathering/android/di/ApplicationModule.kt, app/src/main/java/com/gathering/android/event/home/EventListAdapter.kt, app/src/main/java/com/gathering/android/event/home/EventListViewModel.kt, app/src/main/java/com/gathering/android/event/home/EventViewState.kt, app/src/main/java/com/gathering/android/event/home/HomeFragment.kt, app/src/main/java/com/gathering/android/event/home/model/Event.kt, app/src/main/java/com/gathering/android/navhost/NavHostActivity.kt, app/src/main/java/com/gathering/android/navhost/NavHostViewModel.kt, app/src/main/java/com/gathering/android/navhost/NavHostViewState.kt, app/src/main/java/com/gathering/profile/ProfileFragment.kt, app/src/main/res/drawable/ic_filter.xml, app/src/main/res/drawable/ic_sort.xml, app/src/main/res/layout/act_nav_host.xml, app/src/main/res/layout/frg_home.xml, app/src/main/res/layout/item_event.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
add recycler view and adapter for showing the event 
add event  view model page and use it in the corresponding fragment
add image Loader and its implementation
add activeMutable live data
add some icons
change the home fragment XML file
=> T17:Event home page

app/src/main/java/com/gathering/android/event/home/EventListViewModel.kt, app/src/main/java/com/gathering/android/event/home/FilterDialogFragment.kt, app/src/main/java/com/gathering/android/event/home/HomeFragment.kt, app/src/main/java/com/gathering/android/event/home/model/Event.kt, app/src/main/res/layout/frg_filter_dialog.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
add filter button UI
add filterDialogFragment
modify eventListViewModel,  HomeFragment, and Event.kt accordingly
=> [T19] add Filter button UI and functionality

app/src/main/res/layout/frg_sign_in.xml, app/src/main/res/layout/frg_sign_up.xml
Add ScrollView For SignUp and SignIn pages
=> T21: Add ScrollView for signIn and SignUp page XML

app/src/main/java/com/gathering/android/Application.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailFragment.kt, app/src/main/java/com/gathering/android/event/home/EventListViewModel.kt, app/src/main/java/com/gathering/android/event/home/EventLocationComparator.kt, app/src/main/java/com/gathering/android/event/home/EventsRepository.kt, app/src/main/java/com/gathering/android/event/home/FilterDialogFragment.kt, app/src/main/java/com/gathering/android/event/home/HomeFragment.kt, app/src/main/java/com/gathering/android/event/home/SortDialogFragment.kt, app/src/main/java/com/gathering/android/event/home/model/Event.kt, app/src/main/res/layout/frg_sort_dialog.xml, app/src/main/res/values/dimen.xml
add sort dialog UI
modify EventListViewModel
=> [T18] add sort dialog UI and funtionality

app/build.gradle, app/src/main/java/com/gathering/android/event/myevent/MyEventFragment.kt, app/src/main/java/com/gathering/android/event/myevent/MyEventViewModel.kt, app/src/main/java/com/gathering/android/event/myevent/MyEventViewState.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventViewModel.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventViewState.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/InviteFriendBottomSheet.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/location/AddLocationBottomSheet.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/pic/AddPicBottomSheet.kt, app/src/main/res/drawable/ic_add_circle.xml, app/src/main/res/drawable/ic_add_person.xml, app/src/main/res/layout/bottom_sheet_add_event.xml, app/src/main/res/layout/bottom_sheet_add_location.xml, app/src/main/res/layout/bottom_sheet_add_pic.xml, app/src/main/res/layout/bottom_sheet_invitation.xml, app/src/main/res/layout/frg_event_detail.xml, app/src/main/res/layout/frg_filter_dialog.xml, app/src/main/res/layout/frg_my_event.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
add event bottom sheet fragment
add view_model and ViewState
add UI for adding event fragment
add bottom sheet style
add location/pic/invitation bottom sheet fragment
add location/pic/invitation UI
add some string and dimen
This is not the final UI and ViewModel for adding an event 
We need do some changes to them.
=> T33:Add event bottom sheet

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/gathering/android/common/ImageLoader.kt, app/src/main/java/com/gathering/android/common/ImageLoaderImp.kt, app/src/main/java/com/gathering/android/common/ViewExtensions.kt, app/src/main/java/com/gathering/android/di/InvitationModule.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventViewModel.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventViewState.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/ContactListAdapter.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/InviteFriendBottomSheet.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/model/Contact.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/model/ContactRepository.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/model/ContactRepositoryImpl.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/viewModel/InviteFriendViewModel.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/invitation/viewModel/InviteFriendViewState.kt, app/src/main/res/drawable/ic_delete.xml, app/src/main/res/layout/bottom_sheet_add_event.xml, app/src/main/res/layout/bottom_sheet_invitation.xml, app/src/main/res/layout/item_contact.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml, settings.gradle
add Invite friend bottom sheet 
add Invite friend view state and view model
add contact list adapter
add the repository for retrieving data from the contact provider
=> T32:Add invitation bottom sheet

app/src/main/AndroidManifest.xml, app/src/main/java/com/gathering/android/event/myevent/addevent/pic/AddPicBottomSheet.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/pic/AddPicViewModel.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/pic/AddPicViewState.kt
add ViewModel for AddPicBottpmSheet
add AddPicViewState
add permissionX third party library for granting permissions to use gallery and camera
=> [T36] add viewmodel to addPicBottomSheet

app/src/main/java/com/gathering/android/di/EventModule.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailFragment.kt, app/src/main/java/com/gathering/android/event/home/model/EventsRepository.kt, app/src/main/java/com/gathering/android/event/home/view/EventListAdapter.kt, app/src/main/java/com/gathering/android/event/model/Event.kt, app/src/main/java/com/gathering/android/event/model/EventEntity.kt, app/src/main/java/com/gathering/android/event/model/EventRepositoryImpl.kt, app/src/main/java/com/gathering/android/event/model/User.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventViewModel.kt, app/src/main/res/layout/bottom_sheet_add_event.xml, app/src/main/res/layout/frg_event_detail.xml
add user model and inserting event with new event model
=> T41: Add user model instead of host name

app/src/main/java/com/gathering/android/event/model/EventRepository.kt, app/src/main/java/com/gathering/android/event/model/EventRepositoryImpl.kt, app/src/main/java/com/gathering/android/event/myevent/viewmodel/MyEventViewModel.kt
Add get my event fun to event repository
Call getMyEvent in on resume fun in Event View Model
=> T42: Retrieve user events in my event page

app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
=> [T50] change timePicker style

app/src/main/java/com/gathering/android/auth/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/signin/ForgetPassFragment.kt, app/src/main/java/com/gathering/android/auth/signin/ForgetPasswordViewModel.kt, app/src/main/java/com/gathering/android/auth/signin/ForgetPasswordViewState.kt, app/src/main/java/com/gathering/android/auth/signin/ResetPassInfoBottomSheet.kt, app/src/main/java/com/gathering/android/auth/signin/SignInFragment.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewModel.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewState.kt, app/src/main/java/com/gathering/android/auth/signup/VerificationFragment.kt, app/src/main/res/layout/bottom_sheet_forget_pass_info.xml, app/src/main/res/layout/frg_password_reset.xml, app/src/main/res/layout/frg_sign_in.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/dimen.xml, app/src/main/res/values/strings.xml
add forgetPassFragment and its xml 
add resetPassInfoBottomSheet and its xml
modify signInViewModel 
modify auth repository
add appropriate nav graphs and actions
=> [T24] add forgot password to signIn

app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/res/values/themes.xml
=> T51_change_date_picker_color

app/build.gradle, app/src/main/java/com/gathering/android/auth/signin/SignInFragment.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewModel.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewState.kt, app/src/main/java/com/gathering/android/auth/signin/repo/ApiSignInRepository.kt, app/src/main/java/com/gathering/android/auth/signin/repo/SignInRemoteService.kt, app/src/main/java/com/gathering/android/auth/signin/repo/SignInRepository.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt, app/src/main/java/com/gathering/android/event/model/EventRepositoryImpl.kt, app/src/main/java/com/gathering/android/navhost/di/AuthModule.kt, app/src/main/java/com/gathering/android/navhost/di/NetworkModule.kt
have valid users be able to sign in and show proper messages if the user is not valid or if there are server errors.
=> add proper error messeges - have valid users be able to sign in

app/src/main/java/com/gathering/android/auth/signin/repo/ApiSignInRepository.kt, app/src/main/java/com/gathering/android/common/di/AuthModule.kt, app/src/main/java/com/gathering/android/profile/ProfileFragment.kt, app/src/main/java/com/gathering/android/profile/ProfileViewModel.kt
have user save their profile info , sign out and be able to sign back in with updated user info 
changed onSignUpBtnClicked to onSignOutBtnClicked which was a typo from a separate ticket
=> [T69] sign in user with most recent profile info

app/src/main/java/com/gathering/android/event/Event.kt, app/src/main/java/com/gathering/android/event/EventExtensions.kt, app/src/main/java/com/gathering/android/event/home/EventListViewModel.kt, app/src/main/java/com/gathering/android/event/home/view/EventListAdapter.kt, app/src/main/java/com/gathering/android/event/home/view/HomeFragment.kt, app/src/main/java/com/gathering/android/event/home/viewmodel/EventViewState.kt, app/src/main/java/com/gathering/android/event/model/EventModel.kt, app/src/main/java/com/gathering/android/event/model/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/model/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/model/repo/EventRepository.kt, app/src/main/java/com/gathering/android/event/myevent/addevent/AddEventBottomSheetFragment.kt, app/src/main/res/drawable/ic_liked.xml, app/src/main/res/drawable/ic_unliked.xml, app/src/main/res/layout/frg_profile.xml, app/src/main/res/layout/item_event.xml, app/src/main/res/values/dimen.xml
Add an like event API call
apply some changes to item_event ui
apply some miner changes to homeFragment
apply some miner changes to EventModel
=> Like Event Process

app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordNavigator.kt, app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordScreen.kt, app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordViewModel.kt, app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordViewState.kt, app/src/main/res/layout/screen_new_password_input.xml, app/src/main/res/navigation/nav_graph.xml
- create inputNewPasswordNavigator
- delete viewstate
- change livedata to flow 
- change viewmodel and fragment accordingly 
- rename inputNewPasswordFragment to inputNewPasswordScreen
- change submit button from regular button to a progress bar button 
-
=> [T94] change inputNewPasswordScreen from livedata to flow

app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
- added necessary compose dependencies to build.gradle
- updated kotlin version 
- updated hilt version to be compatible with compose and and kotlin version
=> [T129] enable gathering with jetpack compose dependencies

app/src/main/java/com/gathering/android/auth/signin/SignInScreen.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpScreen.kt, app/src/main/java/com/gathering/android/common/Composables.kt, app/src/main/java/com/gathering/android/ui/theme/Color.kt, app/src/main/java/com/gathering/android/ui/theme/Theme.kt
- got rid of the box component in signInScreen
- added featuerFlag to SignUpScreen 
- changed the padding for customBotton
- got rid of unnecessary imports
- modified the theme
=> [T114] migrate signUpScreen to compose using featureFlag

app/src/main/java/com/gathering/android/auth/signin/SignInScreen.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationScreen.kt, app/src/main/java/com/gathering/android/common/Composables.kt, app/src/main/res/values/strings.xml
- fixed indenting issues 
- got rid of unnessasary imports
- added featureflag 
- added custom error text composable to be used in verification and signIn screen 
- edited a string resource
=> [T115] migrate verificationscreen to comose using feature flag

app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordScreen.kt, app/src/main/java/com/gathering/android/common/Composables.kt, app/src/main/java/com/gathering/android/intro/IntroFragment.kt, app/src/main/res/values/strings.xml
enabling compose on inputNewPasswordScreen by featureFlag
=> [T118] add composable function to inputNewPasswordScreen

app/src/main/java/com/gathering/android/auth/signin/SignInScreen.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpScreen.kt, app/src/main/java/com/gathering/android/intro/IntroFragment.kt
the view was messed up and not taking the full size of the screen , so it had to be fixed!
=> fix fragment view in signIn, signUp and introScreen

app/src/main/java/com/gathering/android/common/Constants.kt, app/src/main/java/com/gathering/android/common/Extentions.kt, app/src/main/java/com/gathering/android/common/PicassoImageLoader.kt, app/src/main/java/com/gathering/android/common/RequestBodyExtentions.kt, app/src/main/java/com/gathering/android/di/ApplicationModule.kt, app/src/main/java/com/gathering/android/profile/ProfileComposables.kt, app/src/main/java/com/gathering/android/profile/ProfileScreen.kt, app/src/main/java/com/gathering/android/profile/ProfileViewModel.kt, app/src/main/java/com/gathering/android/profile/editProfile/EditProfileScreen.kt, app/src/main/java/com/gathering/android/profile/editProfile/EditProfileViewModel.kt, app/src/main/java/com/gathering/android/profile/repo/ApiProfileRepository.kt, app/src/main/java/com/gathering/android/profile/repo/ProfileRemoteService.kt, app/src/main/java/com/gathering/android/profile/repo/ProfileRepository.kt
- Add edit profile composable UI
- Some miner changes on ImageLoader
- Some miner changes on profile screen for make it work smoothly
- Some changes on edit profile and profile viewModel
- Add Extensions on common package for handling Image Url
=> T127 Migrate editProfileScreen to compose

app/src/main/java/com/gathering/android/event/eventdetail/EventDetailComposable.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailScreen.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailUiState.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailViewModel.kt, app/src/main/java/com/gathering/android/home/HomeScreen.kt
- Add compose to event detail compose 
- Add AcceptType to UiState
=> T120 Migrate Event Detail to Compose

app/src/main/java/com/gathering/android/event/eventdetail/EventDetailComposable.kt
- Add spacer in event detail to fix a bug on small size screen
=> T153 Bug fixed event detail screen on small screens

app/src/main/java/com/gathering/android/common/Composables.kt, app/src/main/java/com/gathering/android/event/putevent/pic/AddPicScreen.kt, app/src/main/java/com/gathering/android/profile/ProfileComposables.kt, app/src/main/java/com/gathering/android/profile/ProfileScreen.kt, app/src/main/java/com/gathering/android/profile/editProfile/EditProfileScreen.kt
modified the composable function of ShowImage to be reused in multiple screens
=> [T155] modified composable function and renamed it to be reusable

app/src/main/java/com/gathering/android/event/eventdetail/EventDetailComposable.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailScreen.kt
edited UI for eventDetailScreen
=> [T160] edit UI for EventDetailScreen

app/src/main/java/com/gathering/android/event/putevent/pic/AddPicScreen.kt
the issue was that on my test device which is a pixel 2, open gallery was working but in higher android versions, open gallery was not working and this is why:
**Scoped Storage (Android 10+):** On Android 10 and newer versions, Google introduced scoped storage. Under scoped storage, apps are limited in how they can access files on the device, and they are encouraged to use system-provided file pickers to access files from the user's device. In this case, you typically don't need to request permission to access the gallery because the user selects the files via the system file picker, which is granted permission to access the files.
**Legacy Storage (Android 9 and older):** On Android versions prior to Android 10, you typically need to request permission to access the user's gallery as …
=> [T159] bug fix open gallery not working

app/build.gradle, app/src/main/java/com/gathering/android/common/composables/CustomTextField.kt, app/src/main/java/com/gathering/android/common/composables/ImageViews.kt, app/src/main/java/com/gathering/android/event/attendeeDetail/AttendeesDetailScreen.kt, app/src/main/java/com/gathering/android/event/composables/EventImage.kt, app/src/main/java/com/gathering/android/event/putevent/PutEventScreen.kt, app/src/main/java/com/gathering/android/event/putevent/invitation/AddAttendeeScreen.kt, app/src/main/java/com/gathering/android/event/putevent/location/AddLocationScreen.kt, app/src/main/java/com/gathering/android/event/putevent/location/AddLocationViewModel.kt, app/src/main/java/com/gathering/android/event/putevent/pic/AddPicScreen.kt, app/src/main/java/com/gathering/android/profile/ProfileScreen.kt, app/src/main/java/com/gathering/android/profile/editProfile/EditProfileScreen.kt
This is a group of clean ups on the composables
=> T125 migrate add location to compose WIP

app/src/main/java/com/gathering/android/event/putevent/address/composable/AutoSuggestTextField.kt
add hide keyboard functionality to autoSuggestTextField
=> T166_ event location bug hide keyboard fixed

app/src/main/java/com/gathering/android/common/composables/CustomTextField.kt, app/src/main/java/com/gathering/android/event/putevent/PutEventScreen.kt
Change CustomTextField
Change Put event screen
=> T167 bug fixed put event

app/src/main/java/com/gathering/android/event/putevent/PutEventScreen.kt
Change putEvent screen ->Action button text has been changed for add and edit screen
=> T163 action button text changed

app/src/main/java/com/gathering/android/common/composables/CustomTextField.kt, app/src/main/java/com/gathering/android/event/putevent/invitation/AddAttendeeScreen.kt, app/src/main/java/com/gathering/android/event/putevent/invitation/AddAttendeeUiState.kt, app/src/main/java/com/gathering/android/event/putevent/invitation/AddAttendeesViewModel.kt
add attendee UI state changed 
add attendee Screen and View model changed
custom Text field changed
=> T170 fix bug add attendee

app/src/main/java/com/gathering/android/event/EventComposible.kt, app/src/main/java/com/gathering/android/event/model/EventModel.kt, app/src/main/java/com/gathering/android/event/myevent/MyEventScreen.kt, app/src/main/java/com/gathering/android/event/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/repo/EventRepository.kt, app/src/main/java/com/gathering/android/home/HomeScreen.kt, app/src/main/java/com/gathering/android/home/HomeViewModel.kt
Add get all events 
Handel on Next page  when you scroll
=> T186 add coroutine to get all events

app/src/main/java/com/gathering/android/event/myevent/MyEventViewModel.kt, app/src/main/java/com/gathering/android/event/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/repo/EventException.kt, app/src/main/java/com/gathering/android/event/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/repo/EventRepository.kt, app/src/main/java/com/gathering/android/home/HomeViewModel.kt
change delete fun view
delete delete fun repo and service
=> T198 migrate my event to coroutine part 2

app/src/main/java/com/gathering/android/event/myevent/MyEventViewModel.kt, app/src/main/java/com/gathering/android/event/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/repo/EventException.kt, app/src/main/java/com/gathering/android/event/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/repo/EventRepository.kt, app/src/main/java/com/gathering/android/home/HomeViewModel.kt
add delete event 2 to service evebtRepo and Imp
=> T198 migrate my event to coroutine part 1

app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationViewModel.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt
sendEmailVerification and EmailVerify functions working with coroutine
=> add coroutine to auth repository part 8

app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewModel.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationViewModel.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt
SignUp function working with coroutine
=> add coroutine to auth repository part 7

app/src/main/java/com/gathering/android/auth/AuthException.kt, app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewModel.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewModel.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationViewModel.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt
SignInFunction working with coroutine
=> add coroutine to auth repository part 6

app/src/main/java/com/gathering/android/auth/AuthException.kt, app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordViewModel.kt, app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewModel.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewModel.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationViewModel.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt
resetPassword function working with coroutine
=> add coroutine to auth repository part 5

app/src/main/java/com/gathering/android/auth/AuthException.kt, app/src/main/java/com/gathering/android/auth/password/forgetPassword/ForgetPasswordViewModel.kt, app/src/main/java/com/gathering/android/auth/password/newPassword/InputNewPasswordViewModel.kt, app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/auth/signin/SignInViewModel.kt, app/src/main/java/com/gathering/android/auth/signup/SignUpViewModel.kt, app/src/main/java/com/gathering/android/auth/verification/VerificationViewModel.kt, app/src/main/java/com/gathering/android/common/NetworkExceptions.kt
forgetPassword function working with coroutine
=> add coroutine to auth repository part 4

app/src/main/java/com/gathering/android/auth/AuthException.kt
=> add coroutine to auth repository part 2

app/src/main/java/com/gathering/android/auth/AuthException.kt, app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRemoteService.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt
modify remoteService and repository files
=> add coroutine to auth repository part 1 

app/src/main/java/com/gathering/android/event/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/repo/EventRepository.kt, app/src/main/java/com/gathering/android/profile/favoriteEvent/FavoriteEventScreen.kt, app/src/main/java/com/gathering/android/profile/favoriteEvent/FavoriteEventScreenViewModel.kt
Edit likedEvent service and repo
change loadFavoriteEvent
=> T191 migrate profile to coroutines part 3

app/src/main/java/com/gathering/android/event/ErrorMessages.kt, app/src/main/java/com/gathering/android/event/repo/ApiEventRepository.kt, app/src/main/java/com/gathering/android/event/repo/EventException.kt, app/src/main/java/com/gathering/android/event/repo/EventRemoteService.kt, app/src/main/java/com/gathering/android/event/repo/EventRepository.kt, app/src/main/java/com/gathering/android/profile/favoriteEvent/FavoriteEventScreen.kt, app/src/main/java/com/gathering/android/profile/favoriteEvent/FavoriteEventScreenViewModel.kt
add exception handler and loadFavoriteEvents2
=> T191 migrate profile to coroutines part 2

app/src/main/java/com/gathering/android/auth/repo/ApiAuthRepository.kt, app/src/main/java/com/gathering/android/auth/repo/AuthRepository.kt, app/src/main/java/com/gathering/android/event/ErrorMessages.kt, app/src/main/java/com/gathering/android/event/eventdetail/EventDetailViewModel.kt
fix functions in auth repository to return appropriate response, 
add exception handler in event detail ViewModel
=> fix auth repository and event detail viewmodel 
